/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bowl.glb -k --shadows --transform --exportdefault --simplify 
Files: bowl.glb [1.59MB] > /home/justin/archiflow/public/models/Bowl/bowl-transformed.glb [63.2KB] (96%)
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Bowl/bowl-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Bowl" castShadow receiveShadow geometry={nodes.Vert.geometry} material={materials.Color} />
    </group>
  )
}

useGLTF.preload('/models/Bowl/bowl-transformed.glb')
